// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALEMUobXSsUeGFRUnOVJIKrjOHzaVV62k',
    appId: '1:813982541090:web:c0e8b9280c87bcc11db17b',
    messagingSenderId: '813982541090',
    projectId: 'shopping-app-85846',
    authDomain: 'shopping-app-85846.firebaseapp.com',
    databaseURL: "https://shopping-app-85846-default-rtdb.firebaseio.com/",
    storageBucket: 'shopping-app-85846.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUfySXIIvy32a7rzJ_3W-G46O0SfbKL_o',
    appId: '1:813982541090:android:bc39bcc26bf4f7ee1db17b',
    messagingSenderId: '813982541090',
    projectId: 'shopping-app-85846',
    databaseURL: "https://shopping-app-85846-default-rtdb.firebaseio.com/",
    storageBucket: 'shopping-app-85846.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfTVhV_6awxpeHZYtc8NtMafD-s6SpcA8',
    appId: '1:813982541090:ios:f5cb36c4f56416bb1db17b',
    messagingSenderId: '813982541090',
    projectId: 'shopping-app-85846',
    storageBucket: 'shopping-app-85846.appspot.com',
    iosBundleId: 'com.example.cloneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALEMUobXSsUeGFRUnOVJIKrjOHzaVV62k',
    appId: '1:813982541090:web:4b6761ff018115841db17b',
    messagingSenderId: '813982541090',
    projectId: 'shopping-app-85846',
    authDomain: 'shopping-app-85846.firebaseapp.com',
    storageBucket: 'shopping-app-85846.appspot.com',
  );
}
